on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Test
        run: python -m unittest discover .
  
      
