on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r input.txt
      - name: Install dependencies
        run: pip install -r Biginput.txt
      - name: Run Test
        run: python -m unittest discover .
  
      
